#!/bin/bash
g++ -std=c++11 src/*.cpp  -I/usr/local/include/opencv4/opencv2 -I/usr/local/include/opencv4 -L/usr/local/lib -I/home/AMBOS-PbL/bin -g -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_videoio -lopencv_video -lopencv_dnn -lwiringPi -lcrypt -lmosquitto  -o "bin/AMBOS_PbL"

